#!/bin/bash

dte(){
  dte="$(date +"%A, %B %d | 🕒 %l:%M%p")"
  echo -e "$dte"
}

mem(){
  mem=`free | awk '/Mem/ {printf "%d MiB/%d MiB\n", $3 / 1024.0, $2 / 1024.0 }'`
  echo -e " $mem"
}

cpu(){
  read cpu a b c previdle rest < /proc/stat
  prevtotal=$((a+b+c+previdle))
  sleep 0.5
  read cpu a b c idle rest < /proc/stat
  total=$((a+b+c+idle))
  cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
  echo -e "💻 $cpu% cpu"
}

upd(){
    upd=`checkupdates | wc -l`
    echo -e "$upd Updates"
}

weather(){
    wtr=`curl "wttr.in/38834?format=+%t" &`
    echo -e "$wtr"
}

battery(){
    bat=`(acpi -b | grep 'Battery 1' | awk -F'[,:%]' '{print $2 '-' $3}')`
    echo -e "🔋$(( bat * -1 ))%"
}

while true; do
    xsetroot -name "| $(battery) | $(upd) | $(dte)"
     sleep 1m    # Update time every ten seconds
done &


