#!/usr/bin/env python

import os

path = "/home/logan/Dropbox/PressReports/barcode/"

files = []
# r=root, d=directories, f = files
for r, d, f in os.walk(path):
    for file in f:
        if '.png' in file:
            files.append(file)

for f in files:
    print(os.path.splitext(f)[0])
