#!/bin/bash

#echo $1

case $1 in

  Laptop)
    
#!/bin/sh
    xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP1 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off
      ;;

  HDMI)
    
#!/bin/sh
    xrandr --output eDP1 --off --output DP1 --off --output HDMI1 --primary --mode 1360x768 --pos 0x0 --rotate normal --output HDMI2 --off --output VIRTUAL1 --off
    ;;

  Both)
    
#!/bin/sh
    xrandr --output eDP1 --primary --mode 1920x1080 --pos 1360x0 --rotate normal --output DP1 --off --output HDMI1 --mode 1360x768 --pos 0x0 --rotate normal --output HDMI2 --off --output VIRTUAL1 --off
      ;;
esac
